---
title: "ap1i"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(car)
library(nlme)
library(emmeans)
library(ggplot2)

outputdirectory <- "/Users/jessi/RajLab Dropbox/Jess Li/Shared_JessL/paper/plots/incucyte/t5224/"
```

```{r}
#import data
exp2180 <- read.csv("/Users/jessi/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/t5224/VID2180.csv", header = TRUE)
exp2181 <- read.csv("/Users/jessi/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/t5224/VID2181.csv", header = TRUE)

exp2180 <- exp2180 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2180$exp <- "exp2180"

exp2181 <- exp2181 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2181$exp <- "exp2181"

data <- dplyr::bind_rows(exp2180, exp2181)

```

```{r}
#plot data

# Calculate the average colony for each Name
average_data <- data %>%
  group_by(Name) %>%
  summarize(average_colony = mean(colony))

# Create the plot
plot <- ggplot(data, aes(x = Name, y = colony, fill = exp)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), width = 0.8, alpha = 0.7) +
  geom_bar(data = average_data, aes(x = Name, y = average_colony, fill = Name), stat = "identity", position = position_dodge(width = 0.9), width = 0.8, alpha = 0.4) +
  labs(title = "Bar Graph of Colonies by Name and Experiment",
       x = "Name",
       y = "Colony",
       fill = "Experiment") +
  theme_minimal()
  

  ggsave(filename = paste0(outputdirectory, "n3.pdf"), plot = plot, width = 12, height = 8, device = "pdf")
  
plot  

```

