---
title: "R Notebook"
output: html_notebook

---

```{r, warning=FALSE}
library(viridis)
library(tidyverse)
library(data.table)
library(scales)
library(dplyr)
library(gridExtra)
library(ggplot2)
```

```{r, warning=FALSE}
data_1578 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/ap1reporter/starendscatter/be5/VID1578_C1_1_be5.csv")
data_1578$file_id <- "VID1578"

data_1579 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/ap1reporter/starendscatter/be5/VID1579_C1_1_be5.csv")
data_1579$file_id <- "VID1579"

data_1578$green.blob.Parent.and.child...parentId <- as.numeric(data_1578$green.blob.Parent.and.child...parentId)
data_1578$green.blob.Parent.and.child...childId <- as.numeric(data_1578$green.blob.Parent.and.child...childId)
data_1578$green.blob.Parent.and.child...annotationId <- as.numeric(data_1578$green.blob.Parent.and.child...annotationId)

data_1579$green.blob.Parent.and.child...parentId <- as.numeric(as.character(data_1579$green.blob.Parent.and.child...parentId))
data_1579$green.blob.Parent.and.child...childId <- as.numeric(as.character(data_1579$green.blob.Parent.and.child...childId))
data_1579$green.blob.Parent.and.child...annotationId <- as.numeric(as.character(data_1579$green.blob.Parent.and.child...annotationId))

startenddatac1 <- bind_rows(data_1578, data_1579)

startenddatac1 <- data.frame(lapply(startenddatac1[,c(2:49)], function(x) as.numeric(x)))
# Add back the file_id column
startenddatac1$file_id <- c(rep("VID1578", nrow(data_1578)), rep("VID1579", nrow(data_1579)))

startenddatac1 <- startenddatac1 %>% mutate(
    greencolony = startenddatac1$green.red.Colony.two.color.intensity...Channel.1...MeanColonyIntensity - green.red.Colony.two.color.intensity...Channel.1...MedianIntensity,
    redcolony =  startenddatac1$green.red.Colony.two.color.intensity...Channel.2...MeanColonyIntensity - green.red.Colony.two.color.intensity...Channel.2...MedianIntensity,
    greencell = startenddatac1$green.intensity.measurements...MeanIntensity - startenddatac1$green.Annulus.intensity.measurements...MedianIntensity,
    redcell = startenddatac1$red.intensity.measurements...MeanIntensity - startenddatac1$red.Annulus.intensity.measurements...MedianIntensity,
    parentID = startenddatac1$green.blob.Parent.and.child...parentId,
    childID = startenddatac1$green.blob.Parent.and.child...childId,
    annotationID = startenddatac1$green.blob.Parent.and.child...annotationId
  )


lineageinfo <- startenddatac1 %>% dplyr::select(lineage2 = childID, lineage1 = annotationID, file_id)

#lineageinfo <- data.frame(lapply(lineageinfo, function(x) as.numeric(x)))
lineageinfo <- na.omit(lineageinfo)
lineageinfo <- data.table(lineageinfo)
lineageinfo[, lineageId := .I]

lineagedata_longc1 <- lineageinfo %>%
  pivot_longer(
    cols = c(lineage1, lineage2),  # The columns to pivot
    names_to = "generation",        # New column for generation type
    values_to = "annotationID"      # New column for the annotation ID values
  )

filteredDatac1 <- startenddatac1 %>% dplyr::select(annotationID, greencolony, redcolony, greencell, redcell,file_id)
filteredDatac1$annotationID <- as.numeric(filteredDatac1$annotationID)

lineagedata_longc1 <- left_join(lineagedata_longc1, filteredDatac1, by = c("annotationID", "file_id"))
lineagedata_longc1$lineageId <- factor(lineagedata_longc1$lineageId)


```



```{r}
startingcell <- dplyr::filter(lineagedata_longc1, generation == "lineage1") %>% dplyr::select(lineageId, generation, annotationID, greencell,redcell,file_id)

startingcell$redgreenfc = startingcell$redcell/startingcell$greencell
greenlim = quantile(startingcell$redgreenfc,.25)
redlim = quantile(startingcell$redgreenfc,.75)

startingcell$color <- ifelse(startingcell$redgreenfc > redlim, "red",
                     ifelse(startingcell$redgreenfc < greenlim, "green", "yellow"))
```


```{r}
cellplot <- ggplot(startingcell, aes(x = redcell, y = greencell, colour = color)) +
  geom_point(aes(color = color), size = 1, alpha = 0.9) +
  labs(#title = "Red vs. Generation for Each Lineage",
       x = "Red",
       y = "Green",
       color = "Lineage") +
  theme_minimal() +
  xlim(0,60) +
  ylim(0,120) +
  geom_abline(slope = 1/greenlim, linetype = "dotted", color = "darkgreen") +
  geom_abline(slope = 1/redlim, linetype = "dotted", color = "darkred")


cellplot
```
```{r}
lineageidcolor <- dplyr::select(startingcell, lineageId,color,file_id)

finalcolony <- dplyr::filter(lineagedata_longc1, generation == "lineage2") %>% dplyr::select(lineageId, generation, annotationID, greencolony,redcolony,file_id)

finalcolony <- left_join(finalcolony, lineageidcolor, by = c("lineageId", "file_id"))

finalcolony$redgreenfc = finalcolony$redcolony/finalcolony$greencolony
greenlim = quantile(finalcolony$redgreenfc,.25)
redlim = quantile(finalcolony$redgreenfc,.75)

colonyplot <- ggplot(finalcolony, aes(x = redcolony, y = greencolony, colour = color)) +
  geom_point(aes(color = color), size = 1, alpha = 0.9) +
  labs(#title = "Red vs. Generation for Each Lineage",
       x = "Red",
       y = "Green",
       color = "Lineage") +
  theme_minimal() +
  xlim(0,60) +
  ylim(0,120) +
  geom_abline(slope = 1/greenlim, linetype = "dotted", color = "darkgreen") +
  geom_abline(slope = 1/redlim, linetype = "dotted", color = "darkred")


colonyplot

```



```{r}
cellfile <- "/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/plots/ap1reporter/startendscatter/be5/cellplot.pdf"
ggsave(cellfile, plot = cellplot, width = 10, height = 10, dpi = 300, useDingbats = FALSE)

colonyfile <- "/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/plots/ap1reporter/startendscatter/be5/colonyplot.pdf"
ggsave(colonyfile, plot = colonyplot, width = 10, height = 10, dpi = 300, useDingbats = FALSE)
```

