---
title: "ap1i"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(car)
library(nlme)
library(emmeans)
library(ggplot2)

outputdirectory <- "/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/plots/incucyte/tram/"
```

```{r}
#import data
exp2180 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/t5224/VID2180.csv", header = TRUE)
exp2181 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/t5224/VID2181.csv", header = TRUE)

exp2180 <- exp2180 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2180$exp <- "exp2180"

exp2181 <- exp2181 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2181$exp <- "exp2181"

data1 <- dplyr::bind_rows(exp2180, exp2181)

exp1516 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/jnkin8/VID1516.csv", header = TRUE)
exp2536 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/jnkin8/VID2536.csv", header = TRUE)
exp2112 <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/jnkin8/VID2112.csv", header = TRUE)

exp1516<- exp1516 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp1516$exp <- "exp1516"

exp2536 <- exp2536 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2536$exp <- "exp2536"

exp2112 <- exp2112 %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp2112$exp <- "exp2112"

data2 <- dplyr::bind_rows(exp1516, exp2536) %>% bind_rows(exp2112)

exp1541A <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/tram/1541/VID1541_repA.csv", header = TRUE)
exp1541B <- read.csv("/Users/jess/RajLab Dropbox/Jess Li/Shared_JessL/paper/extractedData/incucyte/tram/1541/VID1541_repB.csv", header = TRUE)

exp1541A<- exp1541A %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp1541A$exp <- "exp1541A"

exp1541B <- exp1541B %>% dplyr::group_by(Name) %>% summarize(colony = n())
exp1541B$exp <- "exp1541B"

data3 <- dplyr::bind_rows(exp1541A, exp1541B)


data <- dplyr::bind_rows(data1, data2) %>% dplyr::bind_rows(data3) %>% dplyr::filter(Name == "hi1" | Name == "lo1" | Name == "lohi1")

```

```{r}
#plot data

# Calculate the average colony for each Name
average_data <- data %>%
  group_by(Name) %>%
  summarize(
    average_colony = mean(colony),
    se_colony = sd(colony) / sqrt(n())
  )

# Create the plot
plot <- ggplot(data, aes(x = Name, y = colony, fill = exp)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), width = 0.8, alpha = 0.7) +
  geom_bar(data = average_data, aes(x = Name, y = average_colony, fill = Name), stat = "identity", position = position_dodge(width = 0.9), width = 0.8, alpha = 0.4) +
  labs(title = "Bar Graph of Colonies by Name and Experiment",
       x = "Name",
       y = "Colony",
       fill = "Experiment") +
  theme_minimal()
  

  ggsave(filename = paste0(outputdirectory, "n3.pdf"), plot = plot, width = 12, height = 8, device = "pdf")
  
plot  

```

```{r}
#get stats

library(nlme)
library(emmeans)
library(car)


# Perform Repeated Measures ANOVA on non-normalized data
model <- lme(colony ~ Name, random = ~1 | exp, data = data)
summary(model)

# Check for normality of residuals
residuals <- residuals(model)
shapiro.test(residuals)

# Check for homogeneity of variances
leveneTest(colony ~ Name, data = data)

# Perform pairwise comparisons using emmeans
emmeans_results <- emmeans(model, pairwise ~ Name, adjust = "holm")
print(emmeans_results)


```

```{r}

data_wide <- spread(data, Name, colony)
print(data_wide)

conditions <- unique(data$Name)
num_conditions <- length(conditions)

p_values <- matrix(NA, nrow = num_conditions, ncol = num_conditions)
rownames(p_values) <- colnames(p_values) <- conditions

for (i in 1:(num_conditions - 1)) {
  for (j in (i + 1):num_conditions) {
    cond_i <- conditions[i]
    cond_j <- conditions[j]
    
    data_i <- data$colony[data$Name == cond_i]
    data_j <- data$colony[data$Name == cond_j]
    
    test_result <- t.test(data_i, data_j, paired = TRUE)
    p_values[i, j] <- p_values[j, i] <- test_result$p.value
  }
}

```

```{r}

summary(emmeans_results$contrasts)$p.value
```






